"""
Email sender service for delivering SEO reports via SMTP.
Converts Markdown reports to styled HTML emails.
Supports weekly scheduled delivery to configured recipients.
"""

import logging
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Optional

import aiosmtplib
from markdown import markdown

from app.core.config import settings

logger = logging.getLogger(__name__)

# HTML email template with responsive styling
EMAIL_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #1a1a2e; max-width: 700px; margin: 0 auto; padding: 20px; background: #f8f9fa; }}
  .container {{ background: #ffffff; border-radius: 12px; padding: 30px; box-shadow: 0 2px 12px rgba(0,0,0,0.08); }}
  .header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 24px 30px; border-radius: 12px 12px 0 0; margin: -30px -30px 20px -30px; }}
  .header h1 {{ margin: 0; font-size: 22px; }}
  .header p {{ margin: 5px 0 0 0; opacity: 0.9; font-size: 14px; }}
  h2 {{ color: #667eea; border-bottom: 2px solid #e8ecf1; padding-bottom: 8px; margin-top: 28px; font-size: 18px; }}
  h3 {{ color: #2d3436; margin-top: 20px; font-size: 16px; }}
  table {{ width: 100%%; border-collapse: collapse; margin: 15px 0; font-size: 14px; }}
  th {{ background: #667eea; color: white; padding: 10px 12px; text-align: left; font-weight: 600; }}
  td {{ padding: 10px 12px; border-bottom: 1px solid #e8ecf1; }}
  tr:nth-child(even) {{ background: #f8f9fa; }}
  .critical {{ background: #fff5f5; border-left: 4px solid #e53e3e; padding: 10px 14px; margin: 8px 0; border-radius: 4px; }}
  .high {{ background: #fffaf0; border-left: 4px solid #dd6b20; padding: 10px 14px; margin: 8px 0; border-radius: 4px; }}
  .medium {{ background: #fffff0; border-left: 4px solid #d69e2e; padding: 10px 14px; margin: 8px 0; border-radius: 4px; }}
  .summary-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(120px, 1fr)); gap: 12px; margin: 16px 0; }}
  .summary-card {{ background: #f8f9fa; border-radius: 8px; padding: 14px; text-align: center; }}
  .summary-card .number {{ font-size: 28px; font-weight: 700; color: #667eea; }}
  .summary-card .label {{ font-size: 12px; color: #718096; margin-top: 4px; }}
  .footer {{ margin-top: 30px; padding-top: 16px; border-top: 1px solid #e8ecf1; font-size: 12px; color: #a0aec0; text-align: center; }}
  code {{ background: #edf2f7; padding: 2px 6px; border-radius: 3px; font-size: 13px; }}
  blockquote {{ background: #f7fafc; border-left: 4px solid #667eea; margin: 12px 0; padding: 10px 16px; color: #4a5568; }}
  a {{ color: #667eea; }}
  ul, ol {{ padding-left: 20px; }}
  li {{ margin: 4px 0; }}
</style>
</head>
<body>
<div class="container">
<div class="header">
  <h1>🧠 Neuronal SEO Report</h1>
  <p>{domain} &mdash; {date}</p>
</div>
{content}
<div class="footer">
  <p>Generated by <strong>Neuronal SEO</strong> on {generated_at}</p>
  <p>Automated SEO Intelligence Pipeline &mdash; {report_type} report</p>
</div>
</div>
</body>
</html>"""


class EmailSender:
    """Sends SEO reports via SMTP with HTML formatting."""

    def __init__(self):
        self.host = settings.smtp_host
        self.port = settings.smtp_port
        self.user = settings.smtp_user
        self.password = settings.smtp_password
        self.enabled = settings.email_enabled

    async def send_report(
        self,
        to_email: str,
        subject: str,
        markdown_content: str,
        domain: str = "",
        report_type: str = "weekly",
    ) -> dict:
        """
        Send a Markdown report as a styled HTML email.

        Args:
            to_email: Recipient email address
            subject: Email subject line
            markdown_content: Report content in Markdown
            domain: Target domain for the report header
            report_type: Type of report (weekly, on_demand, content_brief)

        Returns:
            dict with status and message
        """
        if not self.enabled:
            logger.info("Email sending is disabled in config")
            return {"status": "disabled", "message": "Email sending is not enabled"}

        if not self.host or not self.user:
            logger.warning("SMTP not configured. Set SMTP_HOST, SMTP_USER in .env")
            return {"status": "skipped", "message": "SMTP not configured"}

        try:
            # Convert Markdown to HTML
            html_body = markdown(markdown_content, extensions=["tables", "fenced_code"])

            # Wrap in email template
            now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
            today = datetime.utcnow().strftime("%Y-%m-%d")

            html_email = EMAIL_TEMPLATE.format(
                domain=domain,
                date=today,
                content=html_body,
                generated_at=now,
                report_type=report_type,
            )

            # Build MIME message
            msg = MIMEMultipart("alternative")
            msg["From"] = self.user
            msg["To"] = to_email
            msg["Subject"] = subject
            msg["Date"] = datetime.utcnow().strftime("%a, %d %b %Y %H:%M:%S +0000")

            # Attach both plain text and HTML
            msg.attach(MIMEText(markdown_content[:5000], "plain", "utf-8"))
            msg.attach(MIMEText(html_email, "html", "utf-8"))

            # Send via SMTP
            await aiosmtplib.send(
                msg,
                hostname=self.host,
                port=self.port,
                username=self.user,
                password=self.password,
                use_tls=True,
                timeout=30,
            )

            logger.info(f"Report email sent to {to_email}: {subject}")
            return {"status": "sent", "recipient": to_email, "subject": subject}

        except Exception as e:
            logger.error(f"Failed to send email to {to_email}: {e}")
            return {"status": "error", "message": str(e)}

    async def send_weekly_report(
        self,
        to_email: str,
        markdown_content: str,
        domain: str,
    ) -> dict:
        """Send a weekly SEO report email."""
        now = datetime.utcnow()
        week_num = now.isocalendar()[1]
        year = now.year

        subject = f"SEO Weekly Report — {domain} — Week {week_num}, {year}"

        return await self.send_report(
            to_email=to_email,
            subject=subject,
            markdown_content=markdown_content,
            domain=domain,
            report_type="weekly",
        )

    async def send_content_brief(
        self,
        to_email: str,
        markdown_content: str,
        domain: str,
        page_title: str,
    ) -> dict:
        """Send a content brief for a specific page."""
        subject = f"SEO Content Brief: {page_title} — {domain}"

        return await self.send_report(
            to_email=to_email,
            subject=subject,
            markdown_content=markdown_content,
            domain=domain,
            report_type="content_brief",
        )

    async def send_test_email(self, to_email: str) -> dict:
        """Send a test email to verify SMTP configuration."""
        test_md = f"""# 🧠 Neuronal SEO — SMTP Test

This is a test email from your Neuronal SEO pipeline.

**Configuration:**
- SMTP Host: `{self.host}`
- SMTP Port: `{self.port}`
- From: `{self.user}`

**Time:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}

If you received this, your email configuration is working correctly. ✅

---

Weekly reports will be delivered to this address automatically.
"""

        return await self.send_report(
            to_email=to_email,
            subject="🧠 Neuronal SEO — SMTP Test Email",
            markdown_content=test_md,
            domain="Test",
            report_type="test",
        )
